include_guard(GLOBAL)

set(SGF_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/include/sgf")
set(OUTPUT_HPP "${SGF_INCLUDE_DIR}/sgf.hpp")
    
file(GLOB_RECURSE HPP_FILES 
  RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/include"
  "${SGF_INCLUDE_DIR}/*.hpp"
)
set(CONTENT "// Auto Generated by CMake. Do not edit it.\n")
string(APPEND CONTENT "#pragma once\n\n")

list(SORT HPP_FILES)

foreach(FILE_PATH ${HPP_FILES})
  if(NOT "${FILE_PATH}" STREQUAL "sgf/sgf.hpp")
    string(APPEND CONTENT "#include <${FILE_PATH}>\n")
  endif()
endforeach()

# 先对比新旧内容，避免重复写文件
# compare old and new content to avoid writing file repeatedly

if(EXISTS "${OUTPUT_HPP}")
  file(READ "${OUTPUT_HPP}" OLD_CONTENT)
endif()

if(NOT "${CONTENT}" STREQUAL "${OLD_CONTENT}")
  file(WRITE "${OUTPUT_HPP}" "${CONTENT}")
  message(STATUS "[SGF] All-in-one header sgf.hpp generated.")
else()
  message(STATUS "[SGF] All-in-one header sgf.hpp is already up-to-date.")
endif()