if(MSVC)
  add_compile_options(/utf-8)
endif()

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)

if(SGF_BACKEND_MEDIA STREQUAL "SDL")
  message(STATUS "[SGF] Configuring SDL backend dependencies...")

  if(WIN32)
    set(SDLIMAGE_VENDORED ON CACHE BOOL "" FORCE)
    set(SDLTTF_VENDORED ON CACHE BOOL "" FORCE)
    set(SDLMIXER_VENDORED ON CACHE BOOL "" FORCE)
  endif()

  # SDL3
  set(SDL_SHARED OFF CACHE BOOL "" FORCE)
  set(SDL_STATIC ON CACHE BOOL "" FORCE)
  set(SDL_DISABLE_INSTALL ON CACHE BOOL "" FORCE)
  set(SDL_DISABLE_INSTALL_DOCS ON CACHE BOOL "" FORCE)
  set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
  set(SDL_TESTS OFF CACHE BOOL "" FORCE)
  set(SDL_INSTALL_TESTS OFF CACHE BOOL "" FORCE)
  set(SDL_JACK OFF CACHE BOOL "" FORCE)
  set(SDL_PIPEWIRE OFF CACHE BOOL "" FORCE)

  # SDL3 image
  set(SDLIMAGE_JPG ON CACHE BOOL "" FORCE)
  set(SDLIMAGE_PNG ON CACHE BOOL "" FORCE)
  set(SDLIMAGE_TIF OFF CACHE BOOL "" FORCE)
  set(SDLIMAGE_WEBP OFF CACHE BOOL "" FORCE)
  set(SDLIMAGE_AVIF OFF CACHE BOOL "" FORCE)
  set(SDLIMAGE_AV1 OFF CACHE BOOL "" FORCE)
  set(SDLIMAGE_JXL OFF CACHE BOOL "" FORCE)

  # SDL3 mixer
  set(SDLMIXER_OPUS OFF CACHE BOOL "" FORCE)
  set(SDLMIXER_FLAC OFF CACHE BOOL "" FORCE)
  set(SDLMIXER_GME OFF CACHE BOOL "" FORCE)

  # Auto yasm
  find_program(YASM_PATH NAMES yasm)
  if(NOT YASM_PATH)
    set(YASM_ASSEMBLER "YASM_ASSEMBLER-NOTFOUND" CACHE FILEPATH "" FORCE)
    set(MACHINE "generic" CACHE STRING "" FORCE)
  endif()

  # SDL3 ttf
  set(SDLTTF_HARFBUZZ OFF CACHE BOOL "" FORCE)
endif()

if(SGF_BACKEND_PHYSICS STREQUAL "BOX2D")
  message(STATUS "[SGF] Configuring Box2D settings...")

  set(BOX2D_SAMPLES OFF CACHE BOOL "" FORCE)
  set(BOX2D_UNIT_TESTS OFF CACHE BOOL "" FORCE)
endif()